# Generated by Django 3.2.5 on 2026-04-02 14:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('observacao', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Parada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('emergencial', 'Emergencial'), ('programada', 'Programada')], max_length=20)),
                ('titulo', models.CharField(max_length=255)),
                ('motivo', models.TextField()),
                ('data_inicio', models.DateTimeField()),
                ('data_fim', models.DateTimeField(blank=True, null=True)),
                ('responsavel', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('em_atividade', 'Em atividade'), ('encerrada', 'Encerrada'), ('cancelada', 'Cancelada')], default='em_atividade', max_length=20)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('cadastrante', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paradas_cadastradas', to=settings.AUTH_USER_MODEL)),
                ('municipios_afetados', models.ManyToManyField(related_name='paradas', to='core.Municipio')),
            ],
        ),
        migrations.CreateModel(
            name='Irrigantes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('apelido', models.CharField(blank=True, max_length=255, null=True)),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('rg', models.CharField(blank=True, max_length=20, null=True)),
                ('estado_civil', models.CharField(max_length=50)),
                ('nome_mae', models.CharField(max_length=255)),
                ('data_nascimento', models.DateField()),
                ('conjuge', models.CharField(blank=True, max_length=255, null=True)),
                ('cpf_conjuge', models.CharField(blank=True, max_length=14, null=True)),
                ('rg_conjuge', models.CharField(blank=True, max_length=20, null=True)),
                ('estado_civil_conjuge', models.CharField(blank=True, max_length=50, null=True)),
                ('telefone', models.CharField(max_length=20)),
                ('finalidade', models.TextField(blank=True, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('nome_imovel', models.CharField(max_length=255)),
                ('comunidade', models.CharField(blank=True, max_length=255, null=True)),
                ('area_total', models.DecimalField(decimal_places=2, help_text='Em tarefas', max_digits=10)),
                ('area_irrigada', models.DecimalField(decimal_places=2, max_digits=10)),
                ('forma_ocupacao', models.CharField(max_length=100)),
                ('permissao_de_uso', models.CharField(blank=True, max_length=100, null=True)),
                ('num_permissao', models.CharField(blank=True, max_length=100, null=True)),
                ('uso_individual', models.BooleanField(default=False)),
                ('uso_coletivo', models.BooleanField(default=False)),
                ('quant_coletivo', models.IntegerField(blank=True, null=True)),
                ('num_lacre', models.CharField(blank=True, max_length=100, null=True)),
                ('trecho_captacao', models.CharField(blank=True, max_length=255, null=True)),
                ('vazao_requerida', models.DecimalField(decimal_places=2, help_text='m³/h', max_digits=10)),
                ('potencia_bomba', models.DecimalField(decimal_places=2, help_text='cv', max_digits=10)),
                ('dias_uso_por_semana', models.IntegerField()),
                ('diametro_succao', models.DecimalField(decimal_places=2, max_digits=10)),
                ('diametro_recalque', models.DecimalField(decimal_places=2, max_digits=10)),
                ('energia_utilizada', models.CharField(max_length=100)),
                ('vazao_bombeamento', models.DecimalField(decimal_places=2, max_digits=10)),
                ('distancia_captacao_destinacao', models.DecimalField(decimal_places=2, max_digits=10)),
                ('destinacao_apos_captacao', models.TextField()),
                ('uso_direto', models.BooleanField(default=False)),
                ('uso_reservatorio', models.BooleanField(default=False)),
                ('vol_reservatorio', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('altura_recalque', models.DecimalField(decimal_places=2, max_digits=10)),
                ('termo_autorizacao_semarh', models.FileField(blank=True, null=True, upload_to='termos/')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('cadastrante', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='irrigantes_cadastrados', to=settings.AUTH_USER_MODEL)),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='irrigantes', to='core.municipio')),
            ],
        ),
    ]
