# Generated by Django 3.2.5 on 2026-04-02 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_irrigantes_municipio_parada'),
    ]

    operations = [
        migrations.AddField(
            model_name='municipio',
            name='ativo',
            field=models.BooleanField(default=False),
        ),
    ]
