# Generated by Django 3.2.5 on 2026-04-02 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_municipio_ativo'),
    ]

    operations = [
        migrations.AddField(
            model_name='municipio',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='municipio',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
