# Generated by Django 3.2.5 on 2026-04-07 12:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20260402_1659'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('pai', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategorias', to='core.categoriadocumento')),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='grupo',
            field=models.CharField(blank=True, choices=[('seinfra', 'SEINFRA'), ('casal', 'CASAL'), ('segov', 'SEGOV'), ('seagri', 'SEAGRI'), ('arsal', 'ARSAL'), ('sefaz', 'SEFAZ'), ('iica', 'IICA')], max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('arquivo', models.FileField(upload_to='documentos/')),
                ('descricao', models.TextField(blank=True, null=True)),
                ('data_upload', models.DateTimeField(auto_now_add=True)),
                ('cadastrante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.categoriadocumento')),
            ],
        ),
    ]
