# Generated by Django 3.2.5 on 2026-04-09 13:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20260408_1631'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manifestacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('anonimo', models.BooleanField(default=False)),
                ('tipo', models.CharField(choices=[('denuncia', 'Denúncia'), ('reclamacao', 'Reclamação'), ('solicitacao', 'Solicitação'), ('sugestao', 'Sugestão'), ('elogio', 'Elogio')], max_length=20)),
                ('assunto', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('municipio', models.CharField(blank=True, max_length=150, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('setor_responsavel', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.CharField(choices=[('recebido', 'Recebido'), ('em_analise', 'Em análise'), ('encaminhado', 'Encaminhado'), ('em_andamento', 'Em andamento'), ('concluido', 'Concluído')], default='recebido', max_length=20)),
                ('anexo', models.FileField(blank=True, null=True, upload_to='ouvidoria/')),
                ('protocolo', models.CharField(max_length=20, unique=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('ultima_atualizacao', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Manifestação',
                'verbose_name_plural': 'Manifestações',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.AlterField(
            model_name='projeto',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ManifestacaoHistorico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('recebido', 'Recebido'), ('em_analise', 'Em análise'), ('encaminhado', 'Encaminhado'), ('em_andamento', 'Em andamento'), ('concluido', 'Concluído')], max_length=20)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('manifestacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='core.manifestacao')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
