# Generated by Django 3.2.5 on 2026-04-10 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20260409_1046'),
    ]

    operations = [
        migrations.AddField(
            model_name='manifestacao',
            name='classificacao',
            field=models.CharField(blank=True, choices=[('agropecuaria', 'Agropecuária'), ('consumo_humano', 'Consumo Humano'), ('outros', 'Outros')], max_length=20, null=True),
        ),
    ]
