# Generated by Django 3.2.5 on 2026-04-17 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_manifestacao_classificacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoObra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('data_evento', models.DateField()),
                ('descricao', models.TextField()),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='historico_obra/')),
                ('ordem', models.PositiveIntegerField(default=0, help_text='Usado para ordenar manualmente se necessário')),
            ],
            options={
                'ordering': ['data_evento', 'ordem'],
            },
        ),
    ]
